insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Merle McLugish', 'McLugish', '9396125032', 'mmclugish0@rakuten.co.jp', '2 Tennyson Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Evin Doxey', 'Doxey', '1524145799', 'edoxey1@hhs.gov', '501 Colorado Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Helsa Pashan', 'Pashan', '3859455684', 'hpashan2@shop-pro.jp', '80554 Division Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Woodrow Solano', 'Solano', '5711751225', 'wsolano3@jimdo.com', '1218 Debs Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Annalise Wilkennson', 'Wilkennson', '2617127854', 'awilkennson4@jiathis.com', '50002 South Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Benni Leckey', 'Leckey', '9892559346', 'bleckey5@zdnet.com', '142 Lien Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Latrena Loveday', 'Loveday', '5098930363', 'lloveday6@ow.ly', '7555 Sugar Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Carter Ovenell', 'Ovenell', '5615353955', 'covenell7@furl.net', '756 Atwood Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Katina Falconer', 'Falconer', '8817634396', 'kfalconer8@phoca.cz', '160 Banding Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lyndsie Pollitt', 'Pollitt', '8231558973', 'lpollitt9@ycombinator.com', '055 Ludington Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Nicol Tremeer', 'Tremeer', '8591243875', 'ntremeera@google.nl', '60997 Thackeray Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Brittani Zohrer', 'Zohrer', '1319969363', 'bzohrerb@hp.com', '14020 Hazelcrest Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Harriette Hrinchenko', 'Hrinchenko', '5618645225', 'hhrinchenkoc@flavors.me', '59651 Burrows Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Alessandra Ahmad', 'Ahmad', '5194841795', 'aahmadd@wunderground.com', '32 Stephen Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Garvey McCarroll', 'McCarroll', '5895876480', 'gmccarrolle@com.com', '7214 Meadow Ridge Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Neil Jacquemet', 'Jacquemet', '2963564645', 'njacquemetf@dyndns.org', '54 Anniversary Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Gilberta Jewers', 'Jewers', '7405754041', 'gjewersg@trellian.com', '8533 Moland Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Allin Ossulton', 'Ossulton', '8154365253', 'aossultonh@technorati.com', '430 Blaine Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Stella Laurisch', 'Laurisch', '9202666589', 'slaurischi@irs.gov', '28 Dennis Point');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Cleo Mattiassi', 'Mattiassi', '3106694315', 'cmattiassij@vk.com', '37348 Ridge Oak Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Naomi Kingman', 'Kingman', '9009670317', 'nkingmank@nasa.gov', '9 Randy Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Myrtie Overington', 'Overington', '5847112312', 'moveringtonl@msu.edu', '48926 Center Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Mella Gillion', 'Gillion', '3499671309', 'mgillionm@sciencedaily.com', '62 Esker Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Michelle Rowlson', 'Rowlson', '3586797106', 'mrowlsonn@webmd.com', '9 Schmedeman Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Angelle Lebbern', 'Lebbern', '3465264526', 'alebberno@lulu.com', '95 Miller Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Erma Summerrell', 'Summerrell', '8763388746', 'esummerrellp@unc.edu', '2503 Schlimgen Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Yvonne Cone', 'Cone', '2741297242', 'yconeq@1688.com', '613 Artisan Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Keely Alans', 'Alans', '3365828681', 'kalansr@printfriendly.com', '17 Summer Ridge Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Fin Marians', 'Marians', '2362585267', 'fmarianss@pagesperso-orange.fr', '9 Kedzie Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jammie Gaggen', 'Gaggen', '5537234748', 'jgaggent@about.com', '05 Montana Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jeremy Cadge', 'Cadge', '8829704100', 'jcadgeu@ocn.ne.jp', '6 John Wall Point');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marigold Hanbridge', 'Hanbridge', '1094362930', 'mhanbridgev@nature.com', '83 Loeprich Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Elisabeth McNab', 'McNab', '5824482677', 'emcnabw@fastcompany.com', '7 Golden Leaf Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Egon Camp', 'Camp', '1655812213', 'ecampx@w3.org', '1 Sycamore Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Haleigh Pegrum', 'Pegrum', '8006156377', 'hpegrumy@auda.org.au', '8 Summerview Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ingaborg Tourner', 'Tourner', '8331241302', 'itournerz@sogou.com', '603 Gateway Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Vania Sharer', 'Sharer', '2175145945', 'vsharer10@howstuffworks.com', '83618 Huxley Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Rodolphe Serjeantson', 'Serjeantson', '5178533491', 'rserjeantson11@bravesites.com', '18428 Burning Wood Pass');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Darsie Giffard', 'Giffard', '5858769641', 'dgiffard12@shinystat.com', '4 Loeprich Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ferguson Brattan', 'Brattan', '9246195093', 'fbrattan13@vk.com', '6243 Northview Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ginnifer Goodwins', 'Goodwins', '1533682651', 'ggoodwins14@intel.com', '488 Troy Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Graeme Manuel', 'Manuel', '9861905670', 'gmanuel15@nymag.com', '8 Utah Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Darcee Lorincz', 'Lorincz', '2337232022', 'dlorincz16@cdc.gov', '1 Logan Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Shaw Moyne', 'Moyne', '4183810216', 'smoyne17@cdc.gov', '212 Fair Oaks Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Dulcie Barnardo', 'Barnardo', '6788013435', 'dbarnardo18@cocolog-nifty.com', '38400 Spaight Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Chris Satterthwaite', 'Satterthwaite', '8411156529', 'csatterthwaite19@twitpic.com', '0 Schurz Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Nestor Pablo', 'Pablo', '1605703309', 'npablo1a@123-reg.co.uk', '5 Clarendon Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lorilee Gage', 'Gage', '8758414617', 'lgage1b@bing.com', '2 Riverside Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Monty Kermode', 'Kermode', '9497836924', 'mkermode1c@smugmug.com', '1858 Montana Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Crissy Joll', 'Joll', '1925557810', 'cjoll1d@cargocollective.com', '51 Elmside Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Kendall Paffot', 'Paffot', '4804151659', 'kpaffot1e@usnews.com', '60138 Lakewood Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Giffy Brunini', 'Brunini', '1276909167', 'gbrunini1f@squarespace.com', '654 Clyde Gallagher Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Clywd Goutcher', 'Goutcher', '3431604137', 'cgoutcher1g@shop-pro.jp', '59805 Emmet Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Aidan Glass', 'Glass', '5438676874', 'aglass1h@wikimedia.org', '0 Morrow Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ann Ensten', 'Ensten', '3245763250', 'aensten1i@diigo.com', '3310 Hoepker Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Gertie Jilkes', 'Jilkes', '2442965404', 'gjilkes1j@rediff.com', '44102 Talisman Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Barbara Stenton', 'Stenton', '4165736317', 'bstenton1k@edublogs.org', '69476 Thierer Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Chrisse Cammell', 'Cammell', '2441811407', 'ccammell1l@nationalgeographic.com', '965 Westerfield Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Reamonn Watts', 'Watts', '7018137665', 'rwatts1m@blinklist.com', '14 Bunting Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Franchot O''Dowd', 'O''Dowd', '3005014245', 'fodowd1n@yelp.com', '722 Eagle Crest Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Mattie Porter', 'Porter', '7074046315', 'mporter1o@xinhuanet.com', '4 American Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Towny Crumbleholme', 'Crumbleholme', '2637092323', 'tcrumbleholme1p@cornell.edu', '025 Ronald Regan Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lamar Uwins', 'Uwins', '1809815327', 'luwins1q@instagram.com', '9 Shelley Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Tymon Morville', 'Morville', '2398043902', 'tmorville1r@mac.com', '495 Rusk Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Kaitlin Gronowe', 'Gronowe', '5853227826', 'kgronowe1s@wunderground.com', '70 Dorton Point');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Louella Stables', 'Stables', '3425816958', 'lstables1t@wordpress.com', '1830 Orin Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Berti Bohin', 'Bohin', '7994996492', 'bbohin1u@drupal.org', '55 1st Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ebenezer Beaston', 'Beaston', '2384573903', 'ebeaston1v@reddit.com', '97694 Forster Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Clywd Wheway', 'Wheway', '5605605898', 'cwheway1w@taobao.com', '5 Canary Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lauren McBrearty', 'McBrearty', '2874903564', 'lmcbrearty1x@sun.com', '1 Sherman Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jamison Dunbobbin', 'Dunbobbin', '6749988774', 'jdunbobbin1y@ask.com', '8733 Continental Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Myranda Roderighi', 'Roderighi', '9073964240', 'mroderighi1z@4shared.com', '8 Toban Point');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Zara Cockshott', 'Cockshott', '4402262842', 'zcockshott20@techcrunch.com', '11 Sunbrook Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Alana Villar', 'Villar', '1258125354', 'avillar21@altervista.org', '84 Mockingbird Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marilee Olyonov', 'Olyonov', '4749464795', 'molyonov22@ihg.com', '40 International Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Max Joe', 'Joe', '4816067080', 'mjoe23@bluehost.com', '460 Sutteridge Pass');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Alanson Eliasson', 'Eliasson', '5736325636', 'aeliasson24@tripadvisor.com', '457 Sachs Pass');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Cherilyn Suffe', 'Suffe', '9241389052', 'csuffe25@wikipedia.org', '2969 Bunting Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Yasmin Wibberley', 'Wibberley', '5579775493', 'ywibberley26@squarespace.com', '24 Hintze Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Abby Chalker', 'Chalker', '7856447484', 'achalker27@miibeian.gov.cn', '533 Fallview Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Stoddard Kilban', 'Kilban', '5398777006', 'skilban28@purevolume.com', '81 Knutson Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Rogerio Dolton', 'Dolton', '5392834589', 'rdolton29@blogtalkradio.com', '138 Manitowish Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Chlo Ballister', 'Ballister', '2946353589', 'cballister2a@dell.com', '24940 Northfield Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Dickie Mellon', 'Mellon', '1279545066', 'dmellon2b@npr.org', '2798 Service Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Stanley Kach', 'Kach', '7804559746', 'skach2c@pen.io', '11 Arapahoe Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Briny Wicken', 'Wicken', '7488688846', 'bwicken2d@thetimes.co.uk', '418 John Wall Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Felicle Swede', 'Swede', '4212183380', 'fswede2e@istockphoto.com', '88481 Northfield Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Eldridge Tackes', 'Tackes', '9493408075', 'etackes2f@prnewswire.com', '750 Union Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Mirilla Broom', 'Broom', '7084117048', 'mbroom2g@hibu.com', '668 Waubesa Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Sam Bradbrook', 'Bradbrook', '5631639219', 'sbradbrook2h@oaic.gov.au', '701 South Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Bernette Olenin', 'Olenin', '9552417458', 'bolenin2i@nbcnews.com', '393 Division Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Maryanna Bohey', 'Bohey', '2746107202', 'mbohey2j@cpanel.net', '3 Division Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Myriam Brennon', 'Brennon', '2199061629', 'mbrennon2k@zimbio.com', '3560 Larry Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Millicent Flinders', 'Flinders', '2485622760', 'mflinders2l@digg.com', '2 Steensland Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Gasparo Dunseath', 'Dunseath', '4776901789', 'gdunseath2m@freewebs.com', '12006 Tomscot Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Avivah Aimable', 'Aimable', '2247069274', 'aaimable2n@squidoo.com', '2444 Hauk Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Frieda Fieldhouse', 'Fieldhouse', '5758419282', 'ffieldhouse2o@w3.org', '3234 Troy Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Avis Elloway', 'Elloway', '5814544887', 'aelloway2p@drupal.org', '4271 Northridge Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Bonita McCoole', 'McCoole', '6136350276', 'bmccoole2q@go.com', '16285 Chive Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Coleman Schrinel', 'Schrinel', '4822107582', 'cschrinel2r@businessinsider.com', '53753 Rieder Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Judi Jobson', 'Jobson', '1541819592', 'jjobson2s@ihg.com', '356 Eagle Crest Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jody McCaughren', 'McCaughren', '5923094694', 'jmccaughren2t@shinystat.com', '953 Blue Bill Park Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Josi Arenson', 'Arenson', '9296846551', 'jarenson2u@so-net.ne.jp', '40370 Oxford Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jemimah Haycraft', 'Haycraft', '1411106076', 'jhaycraft2v@gizmodo.com', '8853 Spohn Pass');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Allyn Gladdolph', 'Gladdolph', '2687822760', 'agladdolph2w@wiley.com', '76 Grayhawk Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Nadya Bloore', 'Bloore', '9032831258', 'nbloore2x@shareasale.com', '81299 Redwing Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Wilie Learmonth', 'Learmonth', '6753738711', 'wlearmonth2y@google.ca', '1318 Stang Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Boote Leisk', 'Leisk', '7563215917', 'bleisk2z@sbwire.com', '70505 Orin Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Crystal Keogh', 'Keogh', '3074944439', 'ckeogh30@samsung.com', '57 Hoffman Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jobina Gascar', 'Gascar', '1079778037', 'jgascar31@newsvine.com', '8 Luster Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Erich Willers', 'Willers', '4408198655', 'ewillers32@un.org', '1497 Hanson Pass');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jasmine Tilford', 'Tilford', '5217045754', 'jtilford33@globo.com', '29 Ridge Oak Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Leonardo Ungerechts', 'Ungerechts', '2178972809', 'lungerechts34@freewebs.com', '48699 Helena Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Griffith Fogarty', 'Fogarty', '9752236207', 'gfogarty35@usatoday.com', '0071 Sugar Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Andria Kunath', 'Kunath', '9812139667', 'akunath36@studiopress.com', '376 Kinsman Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Chere Wankling', 'Wankling', '9977359695', 'cwankling37@economist.com', '094 Randy Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marietta Fishpool', 'Fishpool', '7791277557', 'mfishpool38@ucoz.com', '144 Harbort Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Renata Angrove', 'Angrove', '2766219345', 'rangrove39@bing.com', '613 Truax Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Dahlia Clarridge', 'Clarridge', '6736674141', 'dclarridge3a@twitter.com', '25171 Anhalt Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Dierdre Cargo', 'Cargo', '2338771456', 'dcargo3b@nature.com', '1701 Nancy Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Devy Eginton', 'Eginton', '1569097888', 'deginton3c@admin.ch', '29984 Valley Edge Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Sorcha Osman', 'Osman', '6557785243', 'sosman3d@adobe.com', '87720 Merry Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Retha Bikker', 'Bikker', '7909938918', 'rbikker3e@marketwatch.com', '086 Prairieview Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lydia Rounds', 'Rounds', '5501289573', 'lrounds3f@alibaba.com', '247 Forster Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Othelia Benny', 'Benny', '9068857049', 'obenny3g@bloglovin.com', '32742 Ridgeview Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Blinny Horder', 'Horder', '3075973404', 'bhorder3h@digg.com', '8 Florence Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Kiley Doni', 'Doni', '8857922062', 'kdoni3i@army.mil', '6076 Forest Dale Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Madge Duffy', 'Duffy', '9212825315', 'mduffy3j@reuters.com', '9002 Porter Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ruddie Shelliday', 'Shelliday', '5952352793', 'rshelliday3k@shareasale.com', '0082 Scofield Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Louis Heads', 'Heads', '4466550937', 'lheads3l@patch.com', '6 Macpherson Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Rebekah Eicke', 'Eicke', '8773934349', 'reicke3m@cbc.ca', '838 Johnson Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Dulcia Gadeaux', 'Gadeaux', '9754517588', 'dgadeaux3n@tiny.cc', '758 Thackeray Point');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Andre Willisch', 'Willisch', '1083062100', 'awillisch3o@ameblo.jp', '8 Graceland Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jackie Edmed', 'Edmed', '4209219927', 'jedmed3p@miibeian.gov.cn', '9 Ohio Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Zea Ransley', 'Ransley', '3456485458', 'zransley3q@latimes.com', '94 Mcbride Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Gipsy Danilovic', 'Danilovic', '3551114644', 'gdanilovic3r@sciencedirect.com', '451 Killdeer Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Roth Montacute', 'Montacute', '4042831087', 'rmontacute3s@spotify.com', '543 Starling Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Jocelin Sopper', 'Sopper', '4033970616', 'jsopper3t@reference.com', '06930 Blue Bill Park Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Stanfield Muro', 'Muro', '6901016272', 'smuro3u@ask.com', '36439 Menomonie Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Harriott Norcott', 'Norcott', '6891586482', 'hnorcott3v@wiley.com', '930 Oak Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Timoteo Verriour', 'Verriour', '4944826260', 'tverriour3w@addthis.com', '0036 Thompson Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Berri Fagan', 'Fagan', '4882706572', 'bfagan3x@usatoday.com', '7679 Morningstar Alley');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Gerik Talby', 'Talby', '7236154998', 'gtalby3y@gov.uk', '074 Dakota Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Carny Mergue', 'Mergue', '4018271477', 'cmergue3z@go.com', '2 Northwestern Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Erhard Soutar', 'Soutar', '9565148047', 'esoutar40@discovery.com', '6 Saint Paul Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Margit Playfoot', 'Playfoot', '7394309851', 'mplayfoot41@woothemes.com', '031 Manufacturers Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marris Pengilly', 'Pengilly', '6682584010', 'mpengilly42@e-recht24.de', '4 Hoepker Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Coletta Esch', 'Esch', '1086800321', 'cesch43@scribd.com', '397 Commercial Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Avrom Scafe', 'Scafe', '9908467721', 'ascafe44@sfgate.com', '4540 Russell Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Zonda Keeltagh', 'Keeltagh', '9556361251', 'zkeeltagh45@amazon.co.jp', '4258 Rutledge Crossing');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lisbeth Schreiner', 'Schreiner', '9756499052', 'lschreiner46@house.gov', '770 Dixon Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Elana Gluyas', 'Gluyas', '1875104532', 'egluyas47@google.com.hk', '1 Coolidge Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Denni Snelle', 'Snelle', '4312200184', 'dsnelle48@whitehouse.gov', '36 Corry Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Nefen Kibel', 'Kibel', '7712567004', 'nkibel49@qq.com', '692 Daystar Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Linn Coston', 'Coston', '8296216587', 'lcoston4a@senate.gov', '73 Marquette Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Aloin Britian', 'Britian', '7778235722', 'abritian4b@unblog.fr', '1 Cascade Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Alessandro Hachette', 'Hachette', '4315126189', 'ahachette4c@histats.com', '794 Garrison Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Rollins Ingolotti', 'Ingolotti', '4767501621', 'ringolotti4d@bandcamp.com', '9602 Graceland Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marshall Scrivinor', 'Scrivinor', '9631772642', 'mscrivinor4e@quantcast.com', '07 Rockefeller Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Philip Pedel', 'Pedel', '3284746040', 'ppedel4f@biglobe.ne.jp', '90 Amoth Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Barby Rawling', 'Rawling', '8993751060', 'brawling4g@desdev.cn', '16 Red Cloud Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Arley Ruzek', 'Ruzek', '9776227716', 'aruzek4h@spiegel.de', '62 Iowa Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Byram Napper', 'Napper', '9188520228', 'bnapper4i@epa.gov', '47409 Northland Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Delia Cripps', 'Cripps', '9163253066', 'dcripps4j@wikia.com', '22 Buell Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marti Hackinge', 'Hackinge', '9216708170', 'mhackinge4k@state.gov', '394 Village Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Josey Jirus', 'Jirus', '7137218044', 'jjirus4l@163.com', '466 Vermont Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Devin Vamplew', 'Vamplew', '1052230970', 'dvamplew4m@yale.edu', '067 David Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Corine Vasiliev', 'Vasiliev', '2014844028', 'cvasiliev4n@senate.gov', '89043 Fallview Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Moise Tembey', 'Tembey', '5738462171', 'mtembey4o@example.com', '30 Brentwood Pass');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Brear Keele', 'Keele', '1906531246', 'bkeele4p@ca.gov', '6242 Harbort Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Yvor Colquite', 'Colquite', '8289794154', 'ycolquite4q@webnode.com', '0487 Namekagon Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Tamra Wiskar', 'Wiskar', '4548349205', 'twiskar4r@cafepress.com', '0588 Redwing Trail');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Florri McColgan', 'McColgan', '5593254544', 'fmccolgan4s@1688.com', '98508 Bunting Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Alyson Damrel', 'Damrel', '1197520292', 'adamrel4t@google.co.jp', '4 Hoepker Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Cami Gillaspy', 'Gillaspy', '5609479674', 'cgillaspy4u@bandcamp.com', '55 Farwell Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lulita Nizard', 'Nizard', '2343865232', 'lnizard4v@fda.gov', '241 Calypso Avenue');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Pearl Sommerscales', 'Sommerscales', '4133097887', 'psommerscales4w@japanpost.jp', '92746 Shoshone Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Arabelle Gerbi', 'Gerbi', '6926014345', 'agerbi4x@blog.com', '3629 Dapin Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Lesley Douce', 'Douce', '8332927172', 'ldouce4y@arizona.edu', '97 Elmside Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Bo Payley', 'Payley', '2983606853', 'bpayley4z@hud.gov', '1 Springview Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Morganne Dobbings', 'Dobbings', '6398191746', 'mdobbings50@live.com', '26 Warrior Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Karlotte Lowrance', 'Lowrance', '1045520696', 'klowrance51@wsj.com', '991 Bunting Road');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Dean MacIlriach', 'MacIlriach', '5846756740', 'dmacilriach52@wunderground.com', '55 Corry Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ring Andreone', 'Andreone', '3725302686', 'randreone53@ezinearticles.com', '87 Michigan Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Carolann Wingrove', 'Wingrove', '2816893000', 'cwingrove54@mozilla.org', '549 Texas Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Burnard Tomasello', 'Tomasello', '5946774611', 'btomasello55@thetimes.co.uk', '724 Artisan Hill');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Olva Brownsill', 'Brownsill', '2773032006', 'obrownsill56@i2i.jp', '79 Waubesa Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Georgina Wolters', 'Wolters', '1065944098', 'gwolters57@ovh.net', '04190 Vera Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Poppy Veal', 'Veal', '7289891466', 'pveal58@java.com', '9 Laurel Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Nickie Conkie', 'Conkie', '2924760031', 'nconkie59@youku.com', '9 Linden Place');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Vita Ravenscroftt', 'Ravenscroftt', '5233523209', 'vravenscroftt5a@admin.ch', '936 Merchant Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Emelia Askey', 'Askey', '1861230698', 'easkey5b@taobao.com', '50 Derek Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Wyatt Nannizzi', 'Nannizzi', '3175983666', 'wnannizzi5c@icq.com', '53 Blue Bill Park Street');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Cindi Bavidge', 'Bavidge', '1939321978', 'cbavidge5d@cloudflare.com', '1 Roth Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Christye Ostrich', 'Ostrich', '3764095953', 'costrich5e@friendfeed.com', '02081 Welch Parkway');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ellene Morcomb', 'Morcomb', '5091319346', 'emorcomb5f@ihg.com', '646 Hanson Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ferdinanda Dewhurst', 'Dewhurst', '6598851548', 'fdewhurst5g@cnn.com', '29864 Bunker Hill Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ira Marchello', 'Marchello', '6908593938', 'imarchello5h@nsw.gov.au', '54858 Park Meadow Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Wesley Reavell', 'Reavell', '6031407537', 'wreavell5i@reference.com', '430 Riverside Junction');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Marya Housegoe', 'Housegoe', '9991150229', 'mhousegoe5j@dell.com', '4034 Forest Dale Court');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Viviene Lafayette', 'Lafayette', '3468989204', 'vlafayette5k@sakura.ne.jp', '481 Butterfield Park');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ade Vautin', 'Vautin', '4861792029', 'avautin5l@google.es', '20 Cambridge Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Ingmar Gilardoni', 'Gilardoni', '1244837744', 'igilardoni5m@com.com', '86 Buell Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Alexi Jannings', 'Jannings', '9774834990', 'ajannings5n@biglobe.ne.jp', '4020 Valley Edge Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Karlis Nozzolii', 'Nozzolii', '5721677695', 'knozzolii5o@mozilla.org', '6498 Myrtle Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Granny Creevy', 'Creevy', '4003689300', 'gcreevy5p@google.pl', '5 Knutson Lane');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Brigit Klimashevich', 'Klimashevich', '1519697904', 'bklimashevich5q@weibo.com', '9 Dapin Way');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Grantham Airey', 'Airey', '1313517542', 'gairey5r@angelfire.com', '59 Straubel Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Eileen McGirr', 'McGirr', '6348746557', 'emcgirr5s@webnode.com', '7 Longview Plaza');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Skipton Sprake', 'Sprake', '4294167668', 'ssprake5t@fc2.com', '80865 North Circle');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Osgood Lovie', 'Lovie', '8176177611', 'olovie5u@slideshare.net', '98256 Welch Terrace');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Finn Bench', 'Bench', '4181386107', 'fbench5v@istockphoto.com', '7142 Northview Center');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Donielle Reckless', 'Reckless', '3765360452', 'dreckless5w@newsvine.com', '22207 Karstens Drive');
insert into Cliente (CNombre, CApellidos, CTelefono, CEmail, CDireccion) values ('Tildy Kiloh', 'Kiloh', '8679162949', 'tkiloh5x@tumblr.com', '8 Bluejay Court');
