insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Mickey', 'Godart', '6535113744', 'mgodart0@goo.ne.jp', '60 Paget Road');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Tracey', 'Errichiello', '5503593718', 'terrichiello1@netscape.com', '5588 Portage Pass');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Dina', 'Lyenyng', '7102481401', 'dlyenyng2@nhs.uk', '7 Michigan Avenue');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Alix', 'Roelofs', '8703405271', 'aroelofs3@geocities.jp', '3244 Fulton Street');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Lori', 'Stenton', '2417698943', 'lstenton4@seesaa.net', '2 Magdeline Junction');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Salaidh', 'Kenlin', '6742056962', 'skenlin5@columbia.edu', '471 Pawling Crossing');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Stavros', 'Guihen', '7137440701', 'sguihen6@merriam-webster.com', '24 Spaight Center');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Rutherford', 'Smaile', '9395046858', 'rsmaile7@fda.gov', '67135 Morningstar Pass');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Briana', 'Swallow', '5313980569', 'bswallow8@devhub.com', '4364 Novick Circle');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Jolynn', 'Hawking', '2646996578', 'jhawking9@yandex.ru', '7063 Portage Crossing');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Maxi', 'Keatley', '3301057374', 'mkeatleya@hao123.com', '50414 Walton Road');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Kit', 'Houldey', '3252808780', 'khouldeyb@state.tx.us', '3 Redwing Alley');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Filmore', 'Peel', '1909073531', 'fpeelc@telegraph.co.uk', '3 Artisan Center');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Cly', 'Beldon', '1638246808', 'cbeldond@jigsy.com', '6752 Bartelt Parkway');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Cherlyn', 'Denholm', '9856058717', 'cdenholme@fda.gov', '405 Rusk Circle');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Rollo', 'Keel', '1062673498', 'rkeelf@bizjournals.com', '3 Hallows Hill');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Stacy', 'Veschambre', '5591927427', 'sveschambreg@arstechnica.com', '79 American Ash Parkway');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Brittne', 'Gudyer', '5708943680', 'bgudyerh@printfriendly.com', '7818 Huxley Alley');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Elysha', 'Eastbrook', '2894586409', 'eeastbrooki@hibu.com', '379 Old Shore Parkway');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Ashien', 'Heaney`', '6924095263', 'aheaneyj@last.fm', '65718 Raven Crossing');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Beverlie', 'von Nassau', '1797815402', 'bvonnassauk@pagesperso-orange.fr', '1878 Sheridan Hill');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Gusella', 'Ollive', '9395272812', 'gollivel@wikispaces.com', '2 Independence Hill');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Felix', 'Pellington', '6776154838', 'fpellingtonm@netvibes.com', '125 School Center');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Matilda', 'Trodden', '8165166088', 'mtroddenn@google.it', '8002 Monterey Junction');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Aurelie', 'Neem', '5394833180', 'aneemo@over-blog.com', '96 Heffernan Hill');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Shelagh', 'Leifer', '7941065125', 'sleiferp@gov.uk', '82 Mayfield Junction');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Marwin', 'Ashdown', '4152418710', 'mashdownq@psu.edu', '75256 Artisan Alley');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Jeff', 'Atherton', '2258825038', 'jathertonr@weather.com', '982 Columbus Center');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Barbey', 'Vell', '8248137377', 'bvells@jalbum.net', '0736 8th Trail');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Sandi', 'Rourke', '9328047929', 'srourket@house.gov', '7 Charing Cross Pass');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Evan', 'Tarzey', '5696034874', 'etarzeyu@phoca.cz', '83533 Armistice Lane');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Estelle', 'Applegarth', '8167939446', 'eapplegarthv@dion.ne.jp', '620 Dovetail Center');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Alejandra', 'Capozzi', '4878794733', 'acapozziw@wordpress.com', '3138 Little Fleur Pass');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Flory', 'Durnian', '5377965958', 'fdurnianx@about.me', '6325 Blaine Hill');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Kelli', 'Royds', '8801784331', 'kroydsy@constantcontact.com', '05913 Spohn Hill');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Darell', 'De Micoli', '7158729878', 'ddemicoliz@newyorker.com', '80 Melby Court');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Micaela', 'Stonard', '7049639539', 'mstonard10@disqus.com', '0 Anderson Circle');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Napoleon', 'Mazey', '7613580834', 'nmazey11@ycombinator.com', '07 Summer Ridge Road');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Jesselyn', 'Burr', '4414604335', 'jburr12@ibm.com', '7 Mendota Road');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Nataline', 'Kendle', '4744518665', 'nkendle13@facebook.com', '3 Canary Crossing');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Nichole', 'Bury', '6988621523', 'nbury14@i2i.jp', '18368 Welch Way');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Fredericka', 'Marioneau', '5334790438', 'fmarioneau15@homestead.com', '4571 Elka Street');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Mozelle', 'Darlasson', '6658898385', 'mdarlasson16@angelfire.com', '81501 Ryan Junction');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Kliment', 'Geaney', '1973677309', 'kgeaney17@independent.co.uk', '027 Grasskamp Avenue');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Ardelia', 'Broggetti', '7265354471', 'abroggetti18@japanpost.jp', '81395 Waxwing Place');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Elnora', 'Bruun', '2374263108', 'ebruun19@cafepress.com', '4601 Bay Terrace');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Carolee', 'Stones', '9022633842', 'cstones1a@ustream.tv', '5 Saint Paul Junction');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Temple', 'Grzesiewicz', '3146145027', 'tgrzesiewicz1b@columbia.edu', '756 Caliangt Avenue');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Rogers', 'Noury', '6851739334', 'rnoury1c@example.com', '7085 Johnson Trail');
insert into Empleado (ENombre, EApellidos, ETelefono, Eemail, EDireccion) values ('Shep', 'Baumann', '8939732320', 'sbaumann1d@goo.gl', '5 Scofield Pass');
