insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (149, 'Lincoln', 'RET-85-QGN', 'Continental Mark VII', 1985, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (42, 'Dodge', 'GDR-90-TPN', 'Nitro', 2009, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (122, 'Hyundai', 'XXB-91-BWZ', 'Tucson', 2009, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (11, 'GMC', 'LRL-44-YQF', 'Savana 3500', 1996, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (134, 'Dodge', 'RPB-33-LXL', 'Caliber', 2010, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (149, 'Ford', 'DPF-14-DNF', 'Mustang', 1998, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (127, 'Mazda', 'TYU-84-FMH', 'CX-9', 2012, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (153, 'Ford', 'VHU-82-PVZ', 'Bronco', 1989, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (212, 'GMC', 'VXK-00-ODK', 'Rally Wagon 2500', 1992, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (84, 'Chrysler', 'SNA-86-UXA', 'Sebring', 2004, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (104, 'Land Rover', 'LGK-77-UWO', 'LR2', 2012, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (3, 'Kia', 'UIP-93-VZA', 'Optima', 2010, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (39, 'GMC', 'WQK-71-FNT', 'Yukon XL 2500', 2013, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (65, 'Land Rover', 'AZC-86-TZJ', 'Range Rover', 2008, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (29, 'Isuzu', 'SBD-13-BES', 'Rodeo Sport', 2003, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (145, 'Ford', 'AFR-93-YAD', 'E-Series', 2002, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (82, 'Mazda', 'IVA-98-SWS', 'MPV', 1991, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (206, 'Mazda', 'ZTV-05-OGT', 'MX-5', 2009, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (202, 'Mitsubishi', 'KCY-45-HIQ', 'Galant', 1993, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (75, 'Ford', 'BQC-93-YKQ', 'Escort ZX2', 2003, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (37, 'Citroën', 'QAV-91-DJK', 'SM', 1972, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (82, 'Chevrolet', 'SYT-49-EEX', 'Malibu', 2009, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (167, 'Saturn', 'MUA-79-FYT', 'S-Series', 2002, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (109, 'Toyota', 'HZX-58-DJV', 'Land Cruiser', 2001, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (50, 'Ford', 'FWK-75-INV', 'Laser', 1984, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (201, 'Audi', 'XRU-55-GDK', 'A4', 2011, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (10, 'Chevrolet', 'RCI-26-CNA', 'Lumina APV', 1993, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (192, 'GMC', 'WGW-38-IQG', 'Suburban 1500', 1992, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (50, 'GMC', 'VXZ-48-WPR', 'Savana 1500', 2006, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (91, 'Volkswagen', 'BLN-19-THT', 'Passat', 2003, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (173, 'Volkswagen', 'CZX-37-IYA', 'Cabriolet', 1987, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (60, 'Lamborghini', 'JOA-56-HJY', 'Gallardo', 2012, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (123, 'Dodge', 'AQF-37-AGN', 'Ram 1500', 2003, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (52, 'Pontiac', 'FZB-19-IRC', 'Firebird', 1992, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (78, 'Ford', 'GZY-44-VTP', 'Falcon', 1966, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (5, 'BMW', 'XBV-99-MGE', '545', 2005, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (125, 'Chevrolet', 'PTC-13-NSK', 'G-Series G30', 1992, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (23, 'Suzuki', 'EOT-81-JRK', 'Equator', 2009, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (50, 'Ford', 'BLC-81-CCQ', 'LTD Crown Victoria', 1985, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (36, 'Chevrolet', 'JIP-94-AGB', 'Malibu', 2003, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (10, 'Ford', 'MMH-81-YPD', 'F-Series', 2001, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (155, 'Pontiac', 'CAR-31-BCC', 'Sunbird', 1984, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (55, 'Kia', 'HMR-03-ARL', 'Rio', 2003, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (178, 'Acura', 'XCQ-97-ESM', 'CL', 1998, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (112, 'Lexus', 'ULS-62-MRB', 'LS', 2002, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (85, 'Bentley', 'THN-11-JRM', 'Continental GT', 2008, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (86, 'Mercedes-Benz', 'NUE-77-OYV', '190E', 1992, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (3, 'GMC', 'LHA-35-EWD', 'Terrain', 2010, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (35, 'Chevrolet', 'LPS-42-NZT', 'Corvette', 1985, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (192, 'Audi', 'LWG-02-XYT', 'S4', 2008, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (148, 'Chevrolet', 'WRG-12-KJZ', 'Express 3500', 2003, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (34, 'Toyota', 'MPZ-42-VPX', 'Sienna', 2003, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (119, 'Honda', 'VIK-69-QRB', 'Civic', 2010, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (120, 'Mazda', 'EYO-76-EER', 'Mazda6', 2005, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (98, 'GMC', 'WIJ-53-WFM', 'Savana 1500', 1997, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (152, 'Mazda', 'GCA-16-ZWG', 'MPV', 1993, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (11, 'Buick', 'QYY-52-AZH', 'Skylark', 1993, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (207, 'Audi', 'YNR-54-NKI', 'Q7', 2010, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (62, 'Ford', 'BEZ-56-JGR', 'Econoline E150', 1999, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (126, 'Pontiac', 'JOK-54-DHT', 'Bonneville', 1998, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (187, 'Mitsubishi', 'ZMU-89-AUA', 'Galant', 1987, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (53, 'Pontiac', 'DXX-60-UEK', 'Grand Prix', 2005, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (124, 'Ford', 'ESA-13-KYM', 'Taurus', 2008, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (76, 'BMW', 'QTA-17-SDK', '7 Series', 2002, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (91, 'Toyota', 'QDN-96-MNZ', 'Prius', 2002, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (209, 'Citroën', 'AVV-80-VAA', 'SM', 1972, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (101, 'Mitsubishi', 'QFW-34-LEX', 'Mirage', 1987, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (18, 'Nissan', 'FHN-95-VSW', 'Xterra', 2010, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (154, 'Pontiac', 'PHZ-93-ISL', 'Sunbird', 1989, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (153, 'BMW', 'WDL-61-MRY', '3 Series', 2000, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (166, 'Mercury', 'PZF-66-PLW', 'Mountaineer', 2006, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (29, 'Ford', 'ABU-13-XZQ', 'Thunderbird', 1983, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (118, 'Chevrolet', 'YYQ-27-ZUG', 'Corvette', 1953, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (161, 'Audi', 'LMJ-12-FVS', 'A5', 2008, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (164, 'Nissan', 'ZMX-29-ZVS', 'Maxima', 2012, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (79, 'Kia', 'VZD-74-SBH', 'Sedona', 2007, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (70, 'Dodge', 'BMG-94-PDV', 'Charger', 1970, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (152, 'Toyota', 'NSD-60-DIV', 'Tercel', 1995, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (23, 'Subaru', 'NCI-61-PWA', 'Outback', 2007, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (55, 'Toyota', 'UUE-07-IGI', 'Avalon', 1995, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (48, 'Ford', 'JWQ-43-OVH', 'F350', 2006, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (188, 'Ford', 'TAT-82-PNN', 'Bronco', 1994, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (106, 'Mercury', 'YPI-67-ZNZ', 'Cougar', 1997, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (74, 'Mitsubishi', 'IGR-62-VGX', 'Montero Sport', 2004, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (43, 'Dodge', 'IQL-23-SAA', 'Neon', 2000, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (82, 'Lexus', 'FYS-48-EIO', 'GS', 2001, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (165, 'Subaru', 'PEM-04-MCR', 'Legacy', 1996, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (178, 'Audi', 'MBY-46-VQE', '4000CS Quattro', 1986, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (10, 'Bentley', 'HQE-20-PSS', 'Continental Flying Spur', 2007, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (74, 'Mitsubishi', 'UIF-71-PNO', 'Mighty Max Macro', 1993, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (99, 'Mitsubishi', 'SLF-48-YAV', 'Galant', 1984, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (129, 'Volvo', 'PNZ-83-XMA', '940', 1995, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (113, 'Volkswagen', 'CPG-38-DPF', 'Cabriolet', 1985, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (22, 'Mercury', 'PET-20-BZS', 'Cougar', 1984, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (33, 'Lotus', 'QTK-24-HUP', 'Elise', 2005, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (209, 'Volvo', 'DEK-83-GKX', 'C30', 2011, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (200, 'Honda', 'MFA-51-EPO', 'Ridgeline', 2011, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (126, 'Toyota', 'HEX-24-QAU', 'Corolla', 2001, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (50, 'Infiniti', 'QDH-58-TCT', 'G', 2000, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (180, 'Ford', 'VTN-63-UUB', 'Aspire', 1996, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (208, 'Subaru', 'NWV-53-DLB', 'SVX', 1996, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (116, 'Chevrolet', 'XOI-50-PKF', 'Corvette', 1957, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (196, 'Audi', 'QUB-85-YYT', 'R8', 2009, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (6, 'Toyota', 'FAW-16-GZJ', 'Sequoia', 2001, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (88, 'Dodge', 'RTW-99-BSA', 'Nitro', 2007, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (144, 'Dodge', 'NIS-51-XKG', 'Dakota', 1997, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (119, 'Lexus', 'DVK-46-TXM', 'SC', 1998, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (78, 'Aston Martin', 'JOB-01-CEH', 'V8 Vantage', 2008, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (143, 'Land Rover', 'WQQ-64-ONC', 'LR3', 2005, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (203, 'Subaru', 'XGG-87-BRW', 'Outback', 2006, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (66, 'Volkswagen', 'VSK-58-ENZ', 'Phaeton', 2004, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (106, 'Volvo', 'BPV-72-HMX', 'V70', 2008, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (61, 'Land Rover', 'XZJ-12-PHR', 'Discovery', 1997, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (121, 'Buick', 'RFD-43-GGV', 'Regal', 1991, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (3, 'Ford', 'YIK-82-YFI', 'Ranger', 2004, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (140, 'Ford', 'NES-61-QAH', 'EXP', 1985, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (52, 'Ford', 'GAO-17-MIH', 'Explorer', 2001, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (114, 'Chevrolet', 'TBP-78-FHO', 'Suburban', 2007, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (161, 'Oldsmobile', 'WTG-99-OZE', 'Aurora', 2001, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (36, 'Audi', 'NBJ-70-BSA', 'S4', 2006, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (96, 'Chevrolet', 'XMN-78-VDR', 'S10', 2000, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (205, 'Lotus', 'TZG-94-WUN', 'Esprit', 1994, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (80, 'Lexus', 'WVM-84-UFZ', 'GS', 2001, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (45, 'Mercedes-Benz', 'LIK-21-QXT', 'M-Class', 2008, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (143, 'Mercury', 'FNQ-58-VLQ', 'Villager', 1998, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (54, 'Chevrolet', 'QMR-59-CIA', 'Express 2500', 2000, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (160, 'Chevrolet', 'XIH-25-ZKL', 'Express 2500', 2001, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (98, 'Honda', 'SDM-11-CPN', 'Odyssey', 2003, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (185, 'Mazda', 'AYY-69-SLM', 'MX-5', 2011, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (28, 'Buick', 'ZHO-81-UDJ', 'Regal', 1992, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (162, 'Dodge', 'EQI-09-OCC', 'Ram Van 2500', 1999, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (26, 'Ford', 'GEK-88-TIF', 'Crown Victoria', 2010, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (184, 'Audi', 'CZJ-50-GMP', 'Allroad', 2001, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (163, 'Honda', 'QSO-21-CBV', 'Accord', 1985, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (1, 'Audi', 'NGH-50-OSJ', 'riolet', 1995, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (6, 'BMW', 'SYI-83-TGK', 'Z3', 1999, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (5, 'Infiniti', 'DBJ-61-RBC', 'FX', 2003, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (74, 'Mercury', 'BJE-05-XOW', 'Mystique', 1997, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (170, 'Dodge', 'LSQ-95-EWU', 'Dakota Club', 1998, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (8, 'Lincoln', 'APW-19-BZK', 'MKX', 2011, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (12, 'Mazda', 'IYQ-38-OXT', '626', 1999, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (79, 'Chevrolet', 'JFK-98-XEX', 'Cavalier', 1993, 'Violet');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (66, 'Subaru', 'WUL-93-ITQ', 'Alcyone SVX', 1996, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (36, 'Nissan', 'FRT-08-KPT', 'Sentra', 2008, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (214, 'Buick', 'QWT-02-DKF', 'Park Avenue', 2001, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (2, 'Chevrolet', 'CJM-36-AXK', 'S10', 2000, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (13, 'Suzuki', 'CUB-56-IGU', 'Swift', 1994, 'Khaki');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (68, 'Isuzu', 'HJG-27-YHI', 'VehiCROSS', 1999, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (127, 'Chevrolet', 'IRZ-30-JQV', 'Impala', 2000, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (211, 'GMC', 'BKT-78-YQE', 'Envoy XL', 2005, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (100, 'Honda', 'IQQ-03-BYJ', 'Prelude', 1993, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (9, 'Mitsubishi', 'AZB-86-YXL', 'Pajero', 1984, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (7, 'Cadillac', 'MSF-59-YTT', 'Seville', 1993, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (91, 'Chevrolet', 'NDX-66-NMR', 'G-Series G20', 1993, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (175, 'Lexus', 'IHN-02-RLO', 'RX', 2009, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (102, 'Cadillac', 'RNM-14-DTE', 'Eldorado', 1995, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (162, 'Chevrolet', 'NPU-43-KFH', 'Colorado', 2011, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (205, 'Maserati', 'ZPT-84-VWS', '228', 1989, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (38, 'Saturn', 'MVA-79-FIQ', 'VUE', 2008, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (24, 'Ford', 'DQC-38-JRR', 'Ranger', 2000, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (2, 'Land Rover', 'QJP-27-RRM', 'Freelander', 2005, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (30, 'Lexus', 'UBC-47-GOT', 'HS', 2010, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (135, 'Lexus', 'TJJ-80-BRO', 'IS-F', 2012, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (102, 'Suzuki', 'ODJ-43-SEP', 'Vitara', 2000, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (111, 'Citroën', 'UHP-38-NYY', '2CV', 1948, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (157, 'Pontiac', 'KPL-27-PUX', 'Montana', 2006, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (168, 'Mercedes-Benz', 'GEK-46-XRQ', 'E-Class', 1992, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (177, 'BMW', 'NUF-20-WUL', '530', 2005, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (51, 'Plymouth', 'CAW-04-LOY', 'Neon', 1998, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (11, 'Mazda', 'BAZ-06-JAR', 'Mazda6', 2007, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (201, 'Ford', 'ZFW-64-LFY', 'Aerostar', 1994, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (196, 'Volvo', 'MNV-85-BUK', 'S80', 2001, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (6, 'Mazda', 'EPN-35-JOG', 'Miata MX-5', 1999, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (140, 'Ferrari', 'QIN-66-FXC', '599 GTB Fiorano', 2008, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (133, 'Chevrolet', 'YCP-59-VJH', 'HHR Panel', 2006, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (137, 'Hyundai', 'PYA-80-PIS', 'Equus', 2012, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (151, 'Mercedes-Benz', 'XYO-54-QBK', 'E-Class', 1989, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (86, 'Chevrolet', 'TGO-04-FMD', 'Express 3500', 2001, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (63, 'Mazda', 'VCG-42-HMS', '929', 1994, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (206, 'Honda', 'SFC-24-ZBG', 'Accord', 1995, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (95, 'Cadillac', 'TZB-11-ONY', 'CTS', 2010, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (211, 'Lincoln', 'HTZ-33-LAZ', 'Continental', 2002, 'Puce');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (91, 'Mitsubishi', 'HPR-76-EBC', 'Outlander', 2007, 'Orange');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (54, 'Hummer', 'JFJ-39-VNI', 'H1', 1997, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (29, 'Mercedes-Benz', 'JPO-42-TLV', 'E-Class', 1986, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (31, 'Dodge', 'WJC-13-PPF', 'Ram Van B150', 1994, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (113, 'Scion', 'UQC-85-NCU', 'xD', 2008, 'Violet');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (17, 'Subaru', 'CWM-85-AMX', 'SVX', 1992, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (126, 'Infiniti', 'LLT-98-KMW', 'G', 2002, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (62, 'Porsche', 'YLQ-12-ARS', 'Cayman', 2006, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (63, 'Mercury', 'DPI-56-XOD', 'Cougar', 1993, 'Purple');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (97, 'Lotus', 'IRS-81-QWP', 'Esprit', 1994, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (167, 'Jeep', 'KCS-78-SJH', 'Cherokee', 2001, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (3, 'Ford', 'SMF-77-ZWW', 'Escort', 1994, 'Fuscia');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (133, 'Lexus', 'QAN-36-MRJ', 'RX', 2007, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (107, 'Chevrolet', 'RMK-55-OYK', 'Express 2500', 2000, 'Goldenrod');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (9, 'Infiniti', 'VEK-62-UKS', 'FX', 2012, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (208, 'Mercedes-Benz', 'VSV-79-QIL', 'SLS AMG', 2012, 'Crimson');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (165, 'Mercury', 'DSJ-15-TJG', 'Grand Marquis', 2002, 'Green');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (118, 'Chevrolet', 'NOP-66-NPK', 'Corvette', 1984, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (38, 'Hyundai', 'MQU-51-OLM', 'Sonata', 2009, 'Aquamarine');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (38, 'Toyota', 'OUI-57-XEQ', 'Celica', 1982, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (47, 'Chevrolet', 'LVC-03-RFH', 'Camaro', 1978, 'Indigo');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (187, 'Audi', 'JYH-77-WSR', 'A4', 2001, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (120, 'Dodge', 'KJO-19-BKN', 'Nitro', 2010, 'Yellow');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (165, 'Oldsmobile', 'ATP-18-SVT', 'Alero', 2003, 'Pink');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (124, 'Chevrolet', 'SUS-01-OJF', '1500', 1998, 'Mauv');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (177, 'Mercury', 'NRW-90-UCO', 'Lynx', 1986, 'Blue');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (39, 'GMC', 'DBT-19-OVE', 'Suburban 2500', 1994, 'Teal');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (12, 'Ford', 'UVB-04-PDS', 'Expedition', 2007, 'Maroon');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (169, 'Mazda', 'PBX-26-DDQ', 'Mazda3', 2008, 'Violet');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (132, 'Subaru', 'YEV-83-VQC', 'Outback', 2009, 'Turquoise');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (142, 'Chevrolet', 'YGM-60-CVW', 'Suburban 2500', 2004, 'Red');
insert into Vehiculo (ClienteId, VMarca, VPlaca, VModelo, VAño, VColor) values (138, 'Infiniti', 'ENS-37-QDT', 'M', 2009, 'Indigo');
